### PR TITLE
bump to 24 6

### PR DESCRIPTION
**Pull request by saviorand**
This updates the codebase to work with Mojo 24.6.0

Benchmark results with current changes:

```
Benchmark results
--------------------------------------------------------------------------------
name          , met (ms)    , iters   , min (ms)    , mean (ms)   , max (ms)    , duration (ms)
HeaderEncode  ,     0.002075,   571763,     0.002075,     0.002075,     0.002075,  1186.646000
HeaderParse   ,     0.013825,    87064,     0.013825,     0.013825,     0.013825,  1203.660000
RequestEncode ,     0.014535,    88400,     0.014535,     0.014535,     0.014535,  1284.910000
RequestParse  ,     0.059278,    34772,     0.059278,     0.059278,     0.059278,  2061.219000
ResponseEncode,     0.071990,    59699,     0.071990,     0.071990,     0.071990,  4297.749000
ResponseParse ,     0.241491,    10000,     0.241491,     0.241491,     0.241491,  2414.913000
```

### CODE REVIEW

**Comment by saviorand** [comment]
What seems to work:
1. Running server with basic handlers, like `lightbug.🔥`, `bench_server.mojo`
2. Running benchmark with `bench.mojo`
3. No compilation errors 

Some problems with this PR so far:
1. Tests with `magic run test` are failing due to some invalid pointer free errors:
   ```
   
/lightbug_http/tests/lightbug_http/test_client.mojo::test_mojo_client_redirect_external_req_302()


src/tcmalloc.cc:302] Attempt to free invalid pointer 0x14360a8d0 

********************

******************** Failure: '/lightbug_http/tests/lightbug_http/test_client.mojo::test_mojo_client_redirect_external_req_google()' ********************

Unhandled exception caught during execution

/lightbug_http/tests/lightbug_http/test_client.mojo::test_mojo_client_redirect_external_req_google()


src/tcmalloc.cc:302] Attempt to free invalid pointer 0x1357082a0 

   ```
2. When running `mojo run client.mojo` getting an exception, probably related to #1
3. When running `mojo run lightbug.🔥` seeing a lot of "Failed to close connection" logs, looks like from SysConnection.close() method, looks like an issue with `external_call`s?

**Comment by saviorand** [comment]
Also , `small_time` dependency does not have a 24.6 version yet, so had to comment out code related to Cookie expiration date/other datetime.now() usage. Need to make sure this is back before merging this PR

**Comment by saviorand** [comment]
Could the file descriptor issue be related to the symbol clash described by alain on Discord? 
https://discord.com/channels/1087530497313357884/1238682851717812245/1320453635251114095

**Comment by thatstoasty** [comment]
I see you guys are hard at work on 24.6 updates! If there are still some issues when I'm back from vacation I'll try to contribute too!

**Comment by saviorand** [comment]
> I see you guys are hard at work on 24.6 updates! If there are still some issues when I'm back from vacation I'll try to contribute too!

thanks man! I think we'll merge this now, and for remaining fixes/improvements there are a few which we decided to extract into separate issues/PRs, will let you know once those are created
